/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;

/**
 *
 * @author ikhsan
 */
public class FMahasiswa extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    
    public FMahasiswa() {
        initComponents();
        sideHome.setVisible(true);
        txtNama.setBackground(new Color(0,0,0,1));
        txtNISN.setBackground(new Color(0,0,0,1));
        txtNIK.setBackground(new Color(0,0,0,1));
        txttelepon.setBackground(new Color(0,0,0,1));
        txtAlamat.setBackground(new Color(0,0,0,1));
        txtAsalSkl.setBackground(new Color(0,0,0,1));
        txtNilaiRpt.setBackground(new Color(0,0,0,1));
        txtTLahir.setBackground(new Color(0,0,0,1));
        txtTglLahir.setBackground(new Color(0,0,0,1));
        
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnKeluar1 = new javax.swing.JLabel();
        sideInput = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sideList = new javax.swing.JPanel();
        btnKeluar2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sideHome = new javax.swing.JPanel();
        btnKeluar3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        toppane = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        btnMin = new javax.swing.JLabel();
        pList = new javax.swing.JPanel();
        p2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnedit = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pInput = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtNISN = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel23 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtTglLahir = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtTLahir = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txttelepon = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        txtAsalSkl = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        txtNilaiRpt = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        pHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mahasiswa");
        setLocation(new java.awt.Point(100, 100));
        setName("Fmhs"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(236, 236, 236));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(173, 177, 188));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(173, 177, 188));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_udinus.png"))); // NOI18N
        logo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PMB UDINUS");
        logo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 40));

        sidepane.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        logout.setBackground(new java.awt.Color(100, 106, 123));
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hello, admin");
        logout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 51));
        jLabel8.setText("Online");
        logout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        btnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        btnKeluar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.add(btnKeluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 14, -1, 30));

        sidepane.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 210, 60));

        sideInput.setBackground(new java.awt.Color(173, 177, 188));
        sideInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideInputMouseClicked(evt);
            }
        });
        sideInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/input.png"))); // NOI18N
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideInput.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input Data");
        sideInput.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        sidepane.add(sideInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 50));

        sideList.setBackground(new java.awt.Color(173, 177, 188));
        sideList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideListMouseClicked(evt);
            }
        });
        sideList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list.png"))); // NOI18N
        btnKeluar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideList.add(btnKeluar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("List Mahasiswa");
        sideList.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        sidepane.add(sideList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 50));

        sideHome.setBackground(new java.awt.Color(190, 193, 202));
        sideHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideHomeMouseClicked(evt);
            }
        });
        sideHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homelogo.png"))); // NOI18N
        btnKeluar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideHome.add(btnKeluar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home");
        sideHome.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        sidepane.add(sideHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 580));

        toppane.setBackground(new java.awt.Color(52, 106, 163));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout toppaneLayout = new javax.swing.GroupLayout(toppane);
        toppane.setLayout(toppaneLayout);
        toppaneLayout.setHorizontalGroup(
            toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppaneLayout.createSequentialGroup()
                .addContainerGap(720, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
        toppaneLayout.setVerticalGroup(
            toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(toppane, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 780, 30));

        pList.setBackground(new java.awt.Color(207, 207, 207));
        pList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p2.setBackground(new java.awt.Color(245, 245, 245));

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(48, 85, 134));
        jLabel12.setText("List Mahasiswa Baru");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addContainerGap(565, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        pList.add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 40));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnedit.setBackground(new java.awt.Color(52, 106, 163));
        btnedit.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnedit.setForeground(new java.awt.Color(255, 255, 255));
        btnedit.setText("EDIT");
        btnedit.setBorder(null);
        btnedit.setBorderPainted(false);
        btnedit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditActionPerformed(evt);
            }
        });
        jPanel2.add(btnedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 120, 30));

        btnhapus.setBackground(new java.awt.Color(52, 106, 163));
        btnhapus.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btnhapus.setForeground(new java.awt.Color(255, 255, 255));
        btnhapus.setText("HAPUS");
        btnhapus.setBorder(null);
        btnhapus.setBorderPainted(false);
        btnhapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusActionPerformed(evt);
            }
        });
        jPanel2.add(btnhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 120, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 650, 400));

        pList.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 730, 470));

        bg.add(pList, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 770, 550));

        pInput.setBackground(new java.awt.Color(207, 207, 207));
        pInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p1.setBackground(new java.awt.Color(245, 245, 245));

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(48, 85, 134));
        jLabel11.setText("Input Data Mahasiswa Baru");

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel11)
                .addContainerGap(510, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        pInput.add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 40));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(52, 106, 163));
        jLabel13.setForeground(new java.awt.Color(52, 106, 163));
        jLabel13.setText("______________________________________________");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, -1));

        jLabel17.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(48, 85, 134));
        jLabel17.setText("Nama");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 43, 20));

        txtNama.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNama.setBorder(null);
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 220, 30));

        jButton1.setBackground(new java.awt.Color(52, 106, 163));
        jButton1.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("SIMPAN");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 120, 30));

        jLabel18.setBackground(new java.awt.Color(52, 106, 163));
        jLabel18.setForeground(new java.awt.Color(52, 106, 163));
        jLabel18.setText("______________________________________________");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 230, -1));

        jLabel19.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(48, 85, 134));
        jLabel19.setText("NISN");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 43, 20));

        txtNISN.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNISN.setBorder(null);
        jPanel1.add(txtNISN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 220, 30));

        jLabel20.setBackground(new java.awt.Color(52, 106, 163));
        jLabel20.setForeground(new java.awt.Color(52, 106, 163));
        jLabel20.setText("______________________________________________");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 230, -1));

        jLabel21.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(48, 85, 134));
        jLabel21.setText("Jenis Kelamin");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 20));

        txtNIK.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNIK.setBorder(null);
        jPanel1.add(txtNIK, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 220, 30));

        jLabel22.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(48, 85, 134));
        jLabel22.setText("Agama");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 43, 20));

        jRadioButton1.setText("Laki - Laki");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, -1));

        jRadioButton2.setText("Perempuan");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 90, -1));

        jLabel23.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(48, 85, 134));
        jLabel23.setText("NIK");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 43, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Islam", "Kristen", "Katolik", "Budha", "Hindu", "Lainnya" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 80, -1));

        jLabel24.setBackground(new java.awt.Color(52, 106, 163));
        jLabel24.setForeground(new java.awt.Color(52, 106, 163));
        jLabel24.setText("______________________________________________");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 230, -1));

        jLabel25.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(48, 85, 134));
        jLabel25.setText("Tanggal Lahir");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 80, 20));

        txtTglLahir.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtTglLahir.setBorder(null);
        jPanel1.add(txtTglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 220, 30));

        jLabel26.setBackground(new java.awt.Color(52, 106, 163));
        jLabel26.setForeground(new java.awt.Color(52, 106, 163));
        jLabel26.setText("______________________________________________");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 230, -1));

        jLabel27.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(48, 85, 134));
        jLabel27.setText("Tempat Lahir");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 80, 20));

        txtTLahir.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtTLahir.setBorder(null);
        jPanel1.add(txtTLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 220, 30));

        jLabel28.setBackground(new java.awt.Color(52, 106, 163));
        jLabel28.setForeground(new java.awt.Color(52, 106, 163));
        jLabel28.setText("______________________________________________");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 230, -1));

        txtAlamat.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtAlamat.setBorder(null);
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 220, 30));

        jLabel30.setBackground(new java.awt.Color(52, 106, 163));
        jLabel30.setForeground(new java.awt.Color(52, 106, 163));
        jLabel30.setText("______________________________________________");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 230, -1));

        jLabel31.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(48, 85, 134));
        jLabel31.setText("No. Telepon");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 70, 20));

        txttelepon.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txttelepon.setBorder(null);
        jPanel1.add(txttelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 220, 30));

        jLabel32.setBackground(new java.awt.Color(52, 106, 163));
        jLabel32.setForeground(new java.awt.Color(52, 106, 163));
        jLabel32.setText("______________________________________________");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 230, -1));

        jLabel33.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(48, 85, 134));
        jLabel33.setText("Asal Sekolah");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 100, 20));

        txtAsalSkl.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtAsalSkl.setBorder(null);
        jPanel1.add(txtAsalSkl, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 220, 30));

        jLabel34.setBackground(new java.awt.Color(52, 106, 163));
        jLabel34.setForeground(new java.awt.Color(52, 106, 163));
        jLabel34.setText("______________________________________________");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 230, -1));

        jLabel35.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(48, 85, 134));
        jLabel35.setText("Alamat");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 43, 20));

        jLabel36.setBackground(new java.awt.Color(52, 106, 163));
        jLabel36.setForeground(new java.awt.Color(52, 106, 163));
        jLabel36.setText("______________________________________________");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 230, -1));

        txtNilaiRpt.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        txtNilaiRpt.setBorder(null);
        jPanel1.add(txtNilaiRpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 220, 30));

        jLabel38.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(48, 85, 134));
        jLabel38.setText("Nilai Raport");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 70, 20));

        pInput.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 730, 470));

        bg.add(pInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 770, 550));

        pHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 85, 134));
        jLabel2.setText("Selamat Datang!");
        pHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 50));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 85, 134));
        jLabel5.setText("Program PMB Udinus");
        pHome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        pHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        bg.add(pHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 770, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinMouseClicked

    private void sideHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideHomeMouseClicked
        pHome.setVisible(true);
        pList.setVisible(false);
        pInput.setVisible(false);
        
        sideHome.setBackground(new Color(190,193,202));
        sideInput.setBackground(new Color(173,177,188));
        sideList.setBackground(new Color(173,177,188));
    }//GEN-LAST:event_sideHomeMouseClicked

    private void sideInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideInputMouseClicked
        pHome.setVisible(false);
        pList.setVisible(false);
        pInput.setVisible(true);
        
        sideHome.setBackground(new Color(173,177,188));
        sideInput.setBackground(new Color(190,193,202));
        sideList.setBackground(new Color(173,177,188));
    }//GEN-LAST:event_sideInputMouseClicked

    private void sideListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideListMouseClicked
        pHome.setVisible(false);
        pInput.setVisible(false);
        pList.setVisible(true);
        
        sideHome.setBackground(new Color(173,177,188));
        sideInput.setBackground(new Color(173,177,188));
        sideList.setBackground(new Color(190,193,202));
    }//GEN-LAST:event_sideListMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void btneditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneditActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapusActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnKeluar1;
    private javax.swing.JLabel btnKeluar2;
    private javax.swing.JLabel btnKeluar3;
    private javax.swing.JLabel btnMin;
    private javax.swing.JButton btnedit;
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pInput;
    private javax.swing.JPanel pList;
    private javax.swing.JPanel sideHome;
    private javax.swing.JPanel sideInput;
    private javax.swing.JPanel sideList;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel toppane;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtAsalSkl;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNISN;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNilaiRpt;
    private javax.swing.JTextField txtTLahir;
    private javax.swing.JTextField txtTglLahir;
    private javax.swing.JTextField txttelepon;
    // End of variables declaration//GEN-END:variables
}
