/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import java.awt.Color;

/**
 *
 * @author ikhsan
 */
public class FMahasiswa extends javax.swing.JFrame {

    int mousepX;
    int mousepY;
    
    public FMahasiswa() {
        initComponents();
        sideHome.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        logout = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnKeluar1 = new javax.swing.JLabel();
        sideInput = new javax.swing.JPanel();
        btnKeluar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sideList = new javax.swing.JPanel();
        btnKeluar2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sideHome = new javax.swing.JPanel();
        btnKeluar3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        toppane = new javax.swing.JPanel();
        btnClose = new javax.swing.JLabel();
        btnMin = new javax.swing.JLabel();
        pHome = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pInput = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pList = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mahasiswa");
        setLocation(new java.awt.Point(100, 100));
        setName("Fmhs"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(236, 236, 236));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepane.setBackground(new java.awt.Color(173, 177, 188));
        sidepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setBackground(new java.awt.Color(173, 177, 188));
        logo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo_udinus.png"))); // NOI18N
        logo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PMB UDINUS");
        logo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, 40));

        sidepane.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 70));

        logout.setBackground(new java.awt.Color(100, 106, 123));
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Hello, dinusian");
        logout.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Bahnschrift", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 204, 51));
        jLabel8.setText("Online");
        logout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        btnKeluar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        btnKeluar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.add(btnKeluar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 14, -1, 30));

        sidepane.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 210, 60));

        sideInput.setBackground(new java.awt.Color(173, 177, 188));
        sideInput.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideInputMouseClicked(evt);
            }
        });
        sideInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/input.png"))); // NOI18N
        btnKeluar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideInput.add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Input Data");
        sideInput.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        sidepane.add(sideInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 210, 50));

        sideList.setBackground(new java.awt.Color(173, 177, 188));
        sideList.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideListMouseClicked(evt);
            }
        });
        sideList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/list.png"))); // NOI18N
        btnKeluar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideList.add(btnKeluar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("List Mahasiswa");
        sideList.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        sidepane.add(sideList, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 50));

        sideHome.setBackground(new java.awt.Color(190, 193, 202));
        sideHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideHomeMouseClicked(evt);
            }
        });
        sideHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/homelogo.png"))); // NOI18N
        btnKeluar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sideHome.add(btnKeluar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Home");
        sideHome.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        sidepane.add(sideHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 50));

        bg.add(sidepane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 580));

        toppane.setBackground(new java.awt.Color(52, 106, 163));

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/close.png"))); // NOI18N
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });

        btnMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/min.png"))); // NOI18N
        btnMin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout toppaneLayout = new javax.swing.GroupLayout(toppane);
        toppane.setLayout(toppaneLayout);
        toppaneLayout.setHorizontalGroup(
            toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppaneLayout.createSequentialGroup()
                .addContainerGap(720, Short.MAX_VALUE)
                .addComponent(btnMin, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose)
                .addContainerGap())
        );
        toppaneLayout.setVerticalGroup(
            toppaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toppaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(toppane, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 780, 30));

        pHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 40)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(48, 85, 134));
        jLabel2.setText("Selamat Datang!");
        pHome.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 50));

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(48, 85, 134));
        jLabel5.setText("Calon Mahasiswa Baru Udinus ");
        pHome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        pHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        bg.add(pHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 770, 550));

        pInput.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 40)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(48, 85, 134));
        jLabel11.setText("Ini Input");
        pInput.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 50));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        pInput.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        bg.add(pInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 770, 550));

        pList.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Bahnschrift", 1, 40)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(48, 85, 134));
        jLabel14.setText("Ini List");
        pList.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 320, 50));

        jLabel15.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(48, 85, 134));
        jLabel15.setText("Calon Mahasiswa Baru Udinus ");
        pList.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        pList.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        bg.add(pList, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 770, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        
        this.setLocation(kordinatX-mousepX, kordinatY-mousepY);
    }//GEN-LAST:event_bgMouseDragged

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void btnMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinMouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinMouseClicked

    private void sideHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideHomeMouseClicked
        pHome.setVisible(true);
        pList.setVisible(false);
        pInput.setVisible(false);
        
        sideHome.setBackground(new Color(190,193,202));
        sideInput.setBackground(new Color(173,177,188));
        sideList.setBackground(new Color(173,177,188));
    }//GEN-LAST:event_sideHomeMouseClicked

    private void sideInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideInputMouseClicked
        pHome.setVisible(false);
        pList.setVisible(false);
        pInput.setVisible(true);
        
        sideHome.setBackground(new Color(173,177,188));
        sideInput.setBackground(new Color(190,193,202));
        sideList.setBackground(new Color(173,177,188));
    }//GEN-LAST:event_sideInputMouseClicked

    private void sideListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideListMouseClicked
        pHome.setVisible(false);
        pInput.setVisible(false);
        pList.setVisible(true);
        
        sideHome.setBackground(new Color(173,177,188));
        sideInput.setBackground(new Color(173,177,188));
        sideList.setBackground(new Color(190,193,202));
    }//GEN-LAST:event_sideListMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnKeluar1;
    private javax.swing.JLabel btnKeluar2;
    private javax.swing.JLabel btnKeluar3;
    private javax.swing.JLabel btnMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel logo;
    private javax.swing.JPanel logout;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pInput;
    private javax.swing.JPanel pList;
    private javax.swing.JPanel sideHome;
    private javax.swing.JPanel sideInput;
    private javax.swing.JPanel sideList;
    private javax.swing.JPanel sidepane;
    private javax.swing.JPanel toppane;
    // End of variables declaration//GEN-END:variables
}
